-- ==========================================
-- 🛠️ SUPABASE SQL SETUP - VERSÍCULOS DO DIA
-- ==========================================

-- 1. Criar a Tabela de Versículos
CREATE TABLE IF NOT EXISTS public.verses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    category TEXT NOT NULL,
    reference TEXT NOT NULL,
    text TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Criar a Tabela de Versículo do Dia (Histórico)
CREATE TABLE IF NOT EXISTS public.verse_of_the_day (
    date DATE PRIMARY KEY DEFAULT CURRENT_DATE,
    verse_id UUID NOT NULL REFERENCES public.verses(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Ativar RLS
ALTER TABLE public.verses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.verse_of_the_day ENABLE ROW LEVEL SECURITY;

-- 4. Políticas
CREATE POLICY "Permitir leitura pública de versículos" ON public.verses FOR SELECT TO authenticated USING (true);
CREATE POLICY "Permitir leitura pública de versículo do dia" ON public.verse_of_the_day FOR SELECT TO authenticated USING (true);

-- 5. Inserir Versículos
INSERT INTO public.verses (category, reference, text) VALUES
('CONFIANÇA / FÉ', 'Salmos 23:1', 'O Senhor é o meu pastor; nada me faltará.'),
('CONFIANÇA / FÉ', 'Provérbios 3:5-6', 'Confia no Senhor de todo o teu coração, e não te estribes no teu próprio entendimento.   Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas.'),
('CONFIANÇA / FÉ', 'Hebreus 11:1', 'Ora, a fé é o firme fundamento das coisas que se esperam, e a prova das coisas que não se vêem.'),
('CONFIANÇA / FÉ', 'Isaías 41:10', 'não temas, porque eu sou contigo; não te assombres, porque eu sou teu Deus; eu te fortaleço, e te ajudo, e te sustento com a destra da minha justiça.'),
('CONFIANÇA / FÉ', 'Salmos 37:5', 'Entrega o teu caminho ao Senhor; confia nele, e ele tudo fará.'),
('CONFIANÇA / FÉ', 'Romanos 10:17', 'Logo a fé é pelo ouvir, e o ouvir pela palavra de Cristo.'),
('CONFIANÇA / FÉ', 'Marcos 9:23', 'Ao que lhe disse Jesus: Se podes! - tudo é possível ao que crê.'),
('CONFIANÇA / FÉ', 'Salmos 56:3', 'No dia em que eu temer, hei de confiar em ti.'),
('CONFIANÇA / FÉ', 'João 14:1', 'Não se turbe o vosso coração; credes em Deus, crede também em mim.'),
('CONFIANÇA / FÉ', '2 Coríntios 5:7', '(porque andamos por fé, e não por vista);'),
('ANSIEDADE / PAZ', 'Filipenses 4:6-7', 'Não andeis ansiosos por coisa alguma; antes em tudo sejam os vossos pedidos conhecidos diante de Deus pela oração e súplica com ações de graças;   e a paz de Deus, que excede todo o entendimento, guardará os vossos corações e os vossos pensamentos em Cristo Jesus.'),
('ANSIEDADE / PAZ', 'Mateus 6:34', 'Não vos inquieteis, pois, pelo dia de amanhã; porque o dia de amanhã cuidará de si mesmo. Basta a cada dia o seu mal.'),
('ANSIEDADE / PAZ', '1 Pedro 5:7', 'lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós.'),
('ANSIEDADE / PAZ', 'João 14:27', 'Deixo-vos a paz, a minha paz vos dou; eu não vo-la dou como o mundo a dá. Não se turbe o vosso coração, nem se atemorize.'),
('ANSIEDADE / PAZ', 'Salmos 94:19', 'Quando os cuidados do meu coração se multiplicam, as tuas consolações recreiam a minha alma.'),
('ANSIEDADE / PAZ', 'Isaías 26:3', 'Tu conservarás em paz aquele cuja mente está firme em ti; porque ele confia em ti.'),
('ANSIEDADE / PAZ', 'Colossenses 3:15', 'E a paz de Cristo, para a qual também fostes chamados em um corpo, domine em vossos corações; e sede agradecidos.'),
('ANSIEDADE / PAZ', 'Salmos 34:4', 'Busquei ao Senhor, e ele me respondeu, e de todos os meus temores me livrou.'),
('ANSIEDADE / PAZ', 'Mateus 11:28', 'Vinde a mim, todos os que estai cansados e oprimidos, e eu vos aliviarei.'),
('ANSIEDADE / PAZ', 'Salmos 55:22', 'Lança o teu fardo sobre o Senhor, e ele te susterá; nunca permitirá que o justo seja abalado.'),
('FORÇA / CORAGEM', 'Josué 1:9', 'Não to mandei eu? Esforça-te, e tem bom ânimo; não te atemorizes, nem te espantes; porque o Senhor teu Deus está contigo, por onde quer que andares.'),
('FORÇA / CORAGEM', 'Isaías 40:31', 'mas os que esperam no Senhor renovarão as suas forças; subirão com asas como águias; correrão, e não se cansarão; andarão, e não se fatigarão.'),
('FORÇA / CORAGEM', 'Salmos 18:32', 'Ele é o Deus que me cinge de força e torna perfeito o meu caminho;'),
('FORÇA / CORAGEM', 'Efésios 6:10', 'Finalmente, fortalecei-vos no Senhor e na força do seu poder.'),
('FORÇA / CORAGEM', '2 Timóteo 1:7', 'Porque Deus não nos deu o espírito de covardia, mas de poder, de amor e de moderação.'),
('FORÇA / CORAGEM', 'Salmos 27:1', 'O Senhor é a minha luz e a minha salvação; a quem temerei? O Senhor é a força da minha vida; de quem me recearei?'),
('FORÇA / CORAGEM', 'Romanos 8:31', 'Que diremos, pois, a estas coisas? Se Deus é por nós, quem será contra nós?'),
('FORÇA / CORAGEM', 'Deuteronômio 31:6', 'Sede fortes e corajosos; não temais, nem vos atemorizeis diante deles; porque o Senhor vosso Deus é quem vai convosco. Não vos deixará, nem vos desamparará.'),
('FORÇA / CORAGEM', 'Salmos 46:1', 'Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia.'),
('FORÇA / CORAGEM', 'Filipenses 4:13', 'Posso todas as coisas naquele que me fortalece.'),
('AMOR / RELACIONAMENTOS', '1 Coríntios 13:4-7', 'O amor é sofredor, é benigno; o amor não é invejoso; o amor não se vangloria, não se ensoberbece,   não se porta inconvenientemente, não busca os seus próprios interesses, não se irrita, não suspeita mal;   não se regozija com a injustiça, mas se regozija com a verdade;   tudo sofre, tudo crê, tudo espera, tudo suporta.'),
('AMOR / RELACIONAMENTOS', 'João 15:12', 'O meu mandamento é este: Que vos ameis uns aos outros, assim como eu vos amei.'),
('AMOR / RELACIONAMENTOS', 'Efésios 4:2', 'com toda a humildade e mansidão, com longanimidade, suportando-vos uns aos outros em amor,'),
('AMOR / RELACIONAMENTOS', 'Colossenses 3:13', 'suportando-vos e perdoando-vos uns aos outros, se alguém tiver queixa contra outro; assim como o Senhor vos perdoou, assim fazei vós também.'),
('AMOR / RELACIONAMENTOS', 'Provérbios 17:17', 'O amigo ama em todo o tempo; e para a angústia nasce o irmão.'),
('AMOR / RELACIONAMENTOS', 'Romanos 12:10', 'Amai-vos cordialmente uns aos outros com amor fraternal, preferindo-vos em honra uns aos outros;'),
('AMOR / RELACIONAMENTOS', '1 Pedro 4:8', 'tendo antes de tudo ardente amor uns para com os outros, porque o amor cobre uma multidão de pecados;'),
('AMOR / RELACIONAMENTOS', 'João 13:34', 'Um novo mandamento vos dou: que vos ameis uns aos outros; assim como eu vos amei a vós, que também vós vos ameis uns aos outros.'),
('AMOR / RELACIONAMENTOS', 'Mateus 5:44', 'Eu, porém, vos digo: Amai aos vossos inimigos, e orai pelos que vos perseguem;'),
('AMOR / RELACIONAMENTOS', 'Efésios 4:32', 'Antes sede bondosos uns para com os outros, compassivos, perdoando-vos uns aos outros, como também Deus vos perdoou em Cristo.'),
('PROVISÃO / VIDA', 'Mateus 6:33', 'Mas buscai primeiro o seu reino e a sua justiça, e todas estas coisas vos serão acrescentadas.'),
('PROVISÃO / VIDA', 'Filipenses 4:19', 'Meu Deus suprirá todas as vossas necessidades segundo as suas riquezas na glória em Cristo Jesus.'),
('PROVISÃO / VIDA', 'Salmos 34:10', 'Os leõezinhos necessitam e sofrem fome, mas àqueles que buscam ao Senhor, bem algum lhes faltará.'),
('PROVISÃO / VIDA', 'Lucas 12:24', 'Considerai os corvos, que não semeiam nem ceifam; não têm despensa nem celeiro; contudo, Deus os alimenta. Quanto mais não valeis vós do que as aves!'),
('PROVISÃO / VIDA', 'Provérbios 10:22', 'A bênção do Senhor é que enriquece; e ele não a faz seguir de dor alguma.'),
('PROVISÃO / VIDA', 'Deuteronômio 8:18', 'Antes te lembrarás do Senhor teu Deus, porque ele é o que te dá força para adquirires riquezas; a fim de confirmar o seu pacto, que jurou a teus pais, como hoje se vê.'),
('PROVISÃO / VIDA', 'Salmos 37:25', 'Fui moço, e agora sou velho; mas nunca vi desamparado o justo, nem a sua descendência a mendigar o pão.'),
('PROVISÃO / VIDA', '2 Coríntios 9:8', 'E Deus é poderoso para fazer abundar em vós toda a graça, a fim de que, tendo sempre, em tudo, toda a suficiência, abundeis em toda boa obra;'),
('PROVISÃO / VIDA', 'Hebreus 13:5', 'Seja a vossa vida isenta de ganância, contentando-vos com o que tendes; porque ele mesmo disse: Não te deixarei, nem te desampararei.'),
('PROVISÃO / VIDA', 'Salmos 84:11', 'Porquanto o Senhor Deus é sol e escudo; o Senhor dará graça e glória; não negará bem algum aos que andam na retidão.'),
('PROPÓSITO / DIREÇÃO', 'Jeremias 29:11', 'Pois eu bem sei os planos que estou projetando para vós, diz o Senhor; planos de paz, e não de mal, para vos dar um futuro e uma esperança.'),
('PROPÓSITO / DIREÇÃO', 'Provérbios 16:3', 'Entrega ao Senhor as tuas obras, e teus desígnios serão estabelecidos.'),
('PROPÓSITO / DIREÇÃO', 'Salmos 119:105', 'Lâmpada para os meus pés é a tua palavra, e luz para o meu caminho.'),
('PROPÓSITO / DIREÇÃO', 'Isaías 30:21', 'e os teus ouvidos ouvirão a palavra do que está por detrás de ti, dizendo: Este é o caminho, andai nele; quando vos desviardes para a direita ou para a esquerda.'),
('PROPÓSITO / DIREÇÃO', 'Tiago 1:5', 'Ora, se algum de vós tem falta de sabedoria, peça-a a Deus, que a todos dá liberalmente e não censura, e ser-lhe-á dada.'),
('PROPÓSITO / DIREÇÃO', 'Romanos 8:28', 'E sabemos que todas as coisas concorrem para o bem daqueles que amam a Deus, daqueles que são chamados segundo o seu propósito.'),
('PROPÓSITO / DIREÇÃO', 'Provérbios 19:21', 'Muitos são os planos no coração do homem; mas o desígnio do Senhor, esse prevalecerá.'),
('PROPÓSITO / DIREÇÃO', 'Salmos 32:8', 'Instruir-te-ei, e ensinar-te-ei o caminho que deves seguir; aconselhar-te-ei, tendo-te sob a minha vista.'),
('PROPÓSITO / DIREÇÃO', 'Eclesiastes 3:1', 'Tudo tem a sua ocasião própria, e há tempo para todo propósito debaixo do céu.'),
('PROPÓSITO / DIREÇÃO', 'Colossenses 3:23', 'E tudo quanto fizerdes, fazei-o de coração, como ao Senhor, e não aos homens,'),
('PROTEÇÃO', 'Salmos 91:1-2', 'Aquele que habita no esconderijo do Altíssimo, à sombra do Todo-Poderoso descansará.   Direi do Senhor: Ele é o meu refúgio e a minha fortaleza, o meu Deus, em quem confio.'),
('PROTEÇÃO', 'Salmos 121:7-8', 'O Senhor te guardará de todo o mal; ele guardará a tua vida.   O Senhor guardará a tua saída e a tua entrada, desde agora e para sempre.'),
('PROTEÇÃO', 'Provérbios 18:10', 'Torre forte é o nome do Senhor; para ela corre o justo, e está seguro.'),
('PROTEÇÃO', '2 Tessalonicenses 3:3', 'Mas fiel é o Senhor, o qual vos confirmará e guardará do maligno.'),
('PROTEÇÃO', 'Salmos 46:5', 'Deus está no meio dela; não será abalada; Deus a ajudará desde o raiar da alva.'),
('PROTEÇÃO', 'Isaías 54:17', 'Não prosperará nenhuma arma forjada contra ti; e toda língua que se levantar contra ti em juízo, tu a condenarás; esta é a herança dos servos do Senhor, e a sua justificação que de mim procede, diz o Senhor.'),
('PROTEÇÃO', 'Salmos 34:7', 'O anjo do Senhor acampa-se ao redor dos que o temem, e os livra.'),
('PROTEÇÃO', 'Êxodo 14:14', 'o Senhor pelejará por vós; e vós vos calareis.'),
('PROTEÇÃO', 'Salmos 125:2', 'Como estão os montes ao redor de Jerusalém, assim o Senhor está ao redor do seu povo, desde agora e para sempre.'),
('PROTEÇÃO', 'Provérbios 3:24', 'Quando te deitares, não temerás; sim, tu te deitarás e o teu sono será suave.'),
('GRATIDÃO', '1 Tessalonicenses 5:18', 'Em tudo dai graças; porque esta é a vontade de Deus em Cristo Jesus para convosco.'),
('GRATIDÃO', 'Salmos 107:1', 'Dai graças ao Senhor, porque ele é bom; porque a sua benignidade dura para sempre;'),
('GRATIDÃO', 'Colossenses 3:17', 'E tudo quanto fizerdes por palavras ou por obras, fazei-o em nome do Senhor Jesus, dando por ele graças a Deus Pai.'),
('GRATIDÃO', 'Salmos 136:1', 'Dai graças ao Senhor, porque ele é bom; porque a sua benignidade dura para sempre.'),
('GRATIDÃO', 'Efésios 5:20', 'sempre dando graças por tudo a Deus, o Pai, em nome de nosso Senhor Jesus Cristo,'),
('GRATIDÃO', 'Salmos 118:24', 'Este é o dia que o Senhor fez; regozijemo-nos, e alegremo-nos nele.'),
('GRATIDÃO', 'Filipenses 4:4', 'Regozijai-vos sempre no Senhor; outra vez digo, regozijai- vos.'),
('GRATIDÃO', 'Salmos 100:4', 'Entrai pelas suas portas com ação de graças, e em seus átrios com louvor; dai-lhe graças e bendizei o seu nome.'),
('GRATIDÃO', 'Hebreus 12:28', 'Pelo que, recebendo nós um reino que não pode ser abalado, retenhamos a graça, pela qual sirvamos a Deus agradavelmente, com reverência e temor;'),
('GRATIDÃO', 'Salmos 9:1', 'Eu te louvarei, Senhor, de todo o meu coração; contarei todas as tuas maravilhas.'),
('MANHÃ / ROTINA', 'Salmos 5:3', 'Pela manhã ouves a minha voz, ó Senhor; pela manhã te apresento a minha oração, e vigio.'),
('MANHÃ / ROTINA', 'Lamentações 3:22-23', 'A benignidade do Senhor jamais acaba, as suas misericórdias não têm fim;   renovam-se cada manhã. Grande é a tua fidelidade.'),
('MANHÃ / ROTINA', 'Salmos 143:8', 'Faze-me ouvir da tua benignidade pela manhã, pois em ti confio; faze-me saber o caminho que devo seguir, porque a ti elevo a minha alma.'),
('MANHÃ / ROTINA', 'Salmos 90:14', 'Sacia-nos de manhã com a tua benignidade, para que nos regozijemos e nos alegremos todos os nossos dias.'),
('MANHÃ / ROTINA', 'Isaías 33:2', 'ç Senhor, tem misericórdia de nós; por ti temos esperado. Sê tu o nosso braço cada manhã, como também a nossa salvação no tempo da tribulação.'),
('MANHÃ / ROTINA', 'Salmos 59:16', 'Eu, porém, cantarei a tua força; pela manhã louvarei com alegria a tua benignidade, porquanto tens sido para mim uma fortaleza, e refúgio no dia da minha angústia.'),
('MANHÃ / ROTINA', 'Salmos 30:5', 'Porque a sua ira dura só um momento; no seu favor está a vida. O choro pode durar uma noite; pela manhã, porém, vem o cântico de júbilo.'),
('MANHÃ / ROTINA', 'Marcos 1:35', 'De madrugada, ainda bem escuro, levantou-se, saiu e foi a um lugar deserto, e ali orava.'),
('MANHÃ / ROTINA', 'Salmos 119:147', 'Antecipo-me à alva da manhã e clamo; aguardo com esperança as tuas palavras.'),
('MANHÃ / ROTINA', 'Salmos 63:1', 'Ó Deus, tu és o meu Deus; ansiosamente te busco. A minha alma tem sede de ti; a minha carne te deseja muito em uma terra seca e cansada, onde não há água.'),
('NOITE / DESCANSO', 'Salmos 4:8', 'Em paz me deitarei e dormirei, porque só tu, Senhor, me fazes habitar em segurança.'),
('NOITE / DESCANSO', 'Provérbios 3:24', 'Quando te deitares, não temerás; sim, tu te deitarás e o teu sono será suave.'),
('NOITE / DESCANSO', 'Salmos 127:2', 'Inútil vos será levantar de madrugada, repousar tarde, comer o pão de dores, pois ele supre aos seus amados enquanto dormem.'),
('NOITE / DESCANSO', 'Mateus 11:28', 'Vinde a mim, todos os que estai cansados e oprimidos, e eu vos aliviarei.'),
('NOITE / DESCANSO', 'Salmos 3:5', 'Eu me deito e durmo; acordo, pois o Senhor me sustenta.'),
('NOITE / DESCANSO', 'Eclesiastes 5:12', 'Doce é o sono do trabalhador, quer coma pouco quer muito; mas a saciedade do rico não o deixa dormir.'),
('NOITE / DESCANSO', 'Isaías 26:9', 'Minha alma te deseja de noite; sim, o meu espírito, dentro de mim, diligentemente te busca; porque, quando os teus juízos estão na terra, os moradores do mundo aprendem justiça.'),
('NOITE / DESCANSO', 'Salmos 16:7', 'Bendigo ao Senhor que me aconselha; até os meus rins me ensinam de noite.'),
('NOITE / DESCANSO', 'Jó 11:18', 'E terás confiança, porque haverá esperança; olharás ao redor de ti e repousarás seguro.'),
('NOITE / DESCANSO', 'Salmos 91:5', 'Não temerás os terrores da noite, nem a seta que voe de dia,');
